### PR TITLE
Initial work to add SOK BMS

### PR DESCRIPTION
**Pull request by mdshw5**
This work is adapted from https://github.com/Louisvdw/dbus-serialbattery/issues/350, using specifications drafted from reverse engineering work by @zuccaro. I have yet to test it, so this PR should be considered a work in progress.

### CODE REVIEW

**Comment by fl4p** [comment]
Great, let me know when you tested it and I'll merge

**Comment by fl4p** [comment]
This just caught my eye:
```voltage = (statistics.mean(cells)*4)/1000 ```
you can just write:
```voltage = sum(cells)/1000 ```

Does this BMS only support 4 cells?

**Comment by mdshw5** [comment]
Yes the BMS only supports 4 cells. I have a lot of testing to do, and this is the first time I’ve started a BLE project, so lots to wrap my head around!

**Comment by fl4p** [comment]
Ok cool. I appreciate your effort! let me know if you need any help

**Comment by fl4p** [comment]
Any update? Did you get it to work?

**Comment by mdshw5** [comment]
No, I did not get this to work. After some preliminary testing I lost interest and forgot. It will require quite a bit more hands on time testing and debugging, and I'm not sure when I'll get around to it.

**Pull request merged**
