### PR TITLE
add supervolt bms

### PR DESCRIPTION
**Pull request by fl4p**

### CODE REVIEW

**Comment by Karatzie** [comment]
Hi Fabian.

When do you start with this pull request.
I have installed two supervolt batteries in my campervan.
I manage some things with home assistant in my campervan and I would like to integrate the supervolt batteries in home assistant.

BR
Andreas

**Comment by Karatzie** [comment]
Hi Fabian.

I installed the Abraxotl Supervolt Batmon HA fork.
There is an error in the code. The cell voltage is already corrected in Volt. I deleted the  /1000.0 for the cell voltage and add the /1000.0 at the battery voltage.

It is not possible to add two supervolt batteries into the configuration. Only one battery works.
I have no idea to improve the code to connect multible supervolt batteries.

Can you help me with the code improvement to monitor multiple supervolt batteries?

BR
Andreas

**Comment by fl4p** [comment]
Hi Andreas,
I've just merged it.
Why doesn't it work with more than 1 battery?
Any error messages?

**Comment by Karatzie** [comment]
Hello Fabian.

I tried it again this morning with two batteries and it worked.
Now I will try your merge.

Many greetings
Andreas

**Comment by fl4p** [comment]
Let me know. I didn't implement your /1000 fix so voltages are probably wrong

**Pull request merged**
